// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: app/observatory/fallback/config.proto

package fallback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	SubjectSelector         []string               `protobuf:"bytes,2,rep,name=subject_selector,json=subjectSelector,proto3" json:"subject_selector,omitempty"`
	FallbackSubjectSelector []string               `protobuf:"bytes,6,rep,name=fallback_subject_selector,json=fallbackSubjectSelector,proto3" json:"fallback_subject_selector,omitempty"`
	ProbeUrl                string                 `protobuf:"bytes,3,opt,name=probe_url,json=probeUrl,proto3" json:"probe_url,omitempty"`
	ProbeInterval           int64                  `protobuf:"varint,4,opt,name=probe_interval,json=probeInterval,proto3" json:"probe_interval,omitempty"`
	EnableConcurrency       bool                   `protobuf:"varint,5,opt,name=enable_concurrency,json=enableConcurrency,proto3" json:"enable_concurrency,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_observatory_fallback_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_fallback_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_observatory_fallback_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetSubjectSelector() []string {
	if x != nil {
		return x.SubjectSelector
	}
	return nil
}

func (x *Config) GetFallbackSubjectSelector() []string {
	if x != nil {
		return x.FallbackSubjectSelector
	}
	return nil
}

func (x *Config) GetProbeUrl() string {
	if x != nil {
		return x.ProbeUrl
	}
	return ""
}

func (x *Config) GetProbeInterval() int64 {
	if x != nil {
		return x.ProbeInterval
	}
	return 0
}

func (x *Config) GetEnableConcurrency() bool {
	if x != nil {
		return x.EnableConcurrency
	}
	return false
}

var File_app_observatory_fallback_config_proto protoreflect.FileDescriptor

const file_app_observatory_fallback_config_proto_rawDesc = "" +
	"\n" +
	"%app/observatory/fallback/config.proto\x12\"xray.core.app.observatory.fallback\"\xe2\x01\n" +
	"\x06Config\x12)\n" +
	"\x10subject_selector\x18\x02 \x03(\tR\x0fsubjectSelector\x12:\n" +
	"\x19fallback_subject_selector\x18\x06 \x03(\tR\x17fallbackSubjectSelector\x12\x1b\n" +
	"\tprobe_url\x18\x03 \x01(\tR\bprobeUrl\x12%\n" +
	"\x0eprobe_interval\x18\x04 \x01(\x03R\rprobeInterval\x12-\n" +
	"\x12enable_concurrency\x18\x05 \x01(\bR\x11enableConcurrencyBy\n" +
	"!com.xray.app.observatory.fallbackP\x01Z2github.com/xtls/xray-core/app/observatory/fallback\xaa\x02\x1dXray.App.Observatory.Fallbackb\x06proto3"

var (
	file_app_observatory_fallback_config_proto_rawDescOnce sync.Once
	file_app_observatory_fallback_config_proto_rawDescData []byte
)

func file_app_observatory_fallback_config_proto_rawDescGZIP() []byte {
	file_app_observatory_fallback_config_proto_rawDescOnce.Do(func() {
		file_app_observatory_fallback_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_observatory_fallback_config_proto_rawDesc), len(file_app_observatory_fallback_config_proto_rawDesc)))
	})
	return file_app_observatory_fallback_config_proto_rawDescData
}

var file_app_observatory_fallback_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_observatory_fallback_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.core.app.observatory.fallback.Config
}
var file_app_observatory_fallback_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_observatory_fallback_config_proto_init() }
func file_app_observatory_fallback_config_proto_init() {
	if File_app_observatory_fallback_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_observatory_fallback_config_proto_rawDesc), len(file_app_observatory_fallback_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_observatory_fallback_config_proto_goTypes,
		DependencyIndexes: file_app_observatory_fallback_config_proto_depIdxs,
		MessageInfos:      file_app_observatory_fallback_config_proto_msgTypes,
	}.Build()
	File_app_observatory_fallback_config_proto = out.File
	file_app_observatory_fallback_config_proto_goTypes = nil
	file_app_observatory_fallback_config_proto_depIdxs = nil
}
